### ISSUE TITLE
`ssh-keygen -l` fingerprint support?

### ISSUE THREAD

**Issue by hvisage** [pwnedkeys/pwnedkeys-tools#1]
Would be nice to have that support too instead of the openssl method, as OpenSSH also have elipitic curves and not just RSA

**Comment by mpalmer** [comment]
There's a surprising amount to unpack in this one little sentence.  I'm going to write down a whole bunch of thoughts, and hopefully one or more of them addresses your concern.  If not, feel free to provide more detail about what you're trying to achieve.

* `pwnedkeys-tools` does have the ability to query for an SSH public key (the big line of base64 text after `ssh-<whatever>`), although I didn't update the README to document that development.  That is now fixed.
* An OpenSSH private key is just PKCS#8 ("PEM") already, so that's covered, too.
* The `subjectPublicKeyInfo` structure from which pwnedkeys derives the query fingerprint supports key types other than RSA, including all the OpenSSH-supported NIST elliptic curves, and pwnedkeys supports them (in, I might add, both compressed and uncompressed point form, for your convenience).
* `pwnedkeys` does not (yet) support ed25519/ed448 curves, because the Ruby OpenSSL module does not yet have support for them.  Watch [This Space](https://github.com/ruby/openssl/issues/117) (or I'll end up implementing the necessary bits and pieces myself in the meantime, if I get around to it first)
* The data over which OpenSSH calculates its fingerprint is completely different to the SPKI fingerprint, and there's no way to convert between the two forms, so it'd be a separate query API.
* If you have an OpenSSH public key, you can calculate the SPKI (as `pwnedkeys-tools` already does) and query away.  Alternately, if you don't have an OpenSSH public key (but only have an OpenSSH key fingerprint) then you can't perform cryptographic operations involving the private key anyway so you're not really at any meaningful risk, and thus determining whether a key is exposed isn't really necessary.
* If you're worried about checking for an exposed host key before connecting, you can get the server public key via `ssh-keyscan`, and it then reduces to the problem of searching with an SSH public key, which is already covered by `pwnedkeys-tools`.

**Comment by mpalmer** [comment]
I'm going to close this due to a lack of followup discussion.
